---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Invited lecture in Biogeography class

## Bridging the gap among community ecology, biogeography and macroevolution: moving from patterns to process

### Outline

Detect patterns of biodiversity distribution is an essential feature present in community ecology and biogeographical studies, since using this approach we can test our hypotheses regarding the processes generating those patterns, or, sometimes, elaborate a posteriori explanation to the observed patterns. However, this pattern-oriented approach is not adequate in all the situations to understand the underlying processes in a given assemblage, since similar patterns can be generated by totally different evolutionary processes, and the contrary, very different patterns could be generated by the same ecological/macroevolutionary process.

In this presentation I will show how we can improve our capacity to detect patterns and processes generating the distribution of biological diversity, with a special focus on the analysis of two very popular metrics used for conservation proposes, [Phylogenetic Diversity](https://www.sciencedirect.com/science/article/pii/0006320792912013)  and [Phylogenetic Endemism](https://onlinelibrary.wiley.com/doi/10.1111/j.1365-294X.2009.04311.x). 

I will demonstrate that by ignoring deep-time events in the evolutionary history of lineages can lead to wrong conclusions about the processes affecting the assembly of communities. Further, I will propose a methodological solution to this problem that allows to the development of a new family of metrics of phylogenetic diversity able to decompose the effects of two main processes responsible to shape the distribution of life on earth: historical dispersal and diversification.


